**Table of contents**<a id='toc0_'></a>    
- [2과목 준비 팁 및 유의사항](#toc1_)    
- [출처](#toc2_)    
- [단계](#toc3_)    
  - [데이터 불러오기](#toc3_1_)    
  - [데이터 유형 파악](#toc3_2_)    
  - [전처리](#toc3_3_)    
    - [(0) 편법으로 빨리하기](#toc3_3_1_)    
    - [(1) X, y, train/test 분리](#toc3_3_2_)    
    - [(2) 결측치 처리](#toc3_3_3_)    
    - [(3) 수치형 변수 스케일링](#toc3_3_4_)    
    - [(4) 범주형 변수 인코딩](#toc3_3_5_)    
  - [데이터 분리(train,val)](#toc3_4_)    
  - [모델 학습 및 검증](#toc3_5_)    
  - [평가](#toc3_6_)    
  - [결과 제출](#toc3_7_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

# <a id='toc1_'></a>[2과목 준비 팁 및 유의사항](#toc0_)
- 회귀/분류별 템플릿 만들어서 달달외우고 시험장에서 적절히 변환
- 제출형식 / 조건 꼼꼼히 읽을 것

# <a id='toc2_'></a>[출처](#toc0_)
https://www.youtube.com/watch?v=QtWhHCuVIxA

# <a id='toc3_'></a>[단계](#toc0_)

## <a id='toc3_1_'></a>[데이터 불러오기](#toc0_)

In [ ]:
# import requests

# # path = r'dataset\customer_test.csv' # test
# path = r'dataset\customer_train.csv' # train

# # URL
# # url = "https://dataq.goorm.io/input-file/content?quizIndex=q_Dlldj_1730448300236&fileName=data%2Fcustomer_test.csv"
# url = "https://dataq.goorm.io/input-file/content?quizIndex=q_Dlldj_1730448300236&fileName=data%2Fcustomer_train.csv"
# # 헤더나 다른 필요 데이터가 있다면 아래처럼 추가
# headers = {
#     "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
# }

# # 요청 보내기
# response = requests.get(url, headers=headers)

# # 상태 코드 확인 (200: 성공)
# if response.status_code == 200:
#     # CSV 데이터 출력 (파일로 저장 가능)
#     with open(path, "wb") as file:
#         file.write(response.content)
#     print("CSV 파일이 성공적으로 저장되었습니다.")
# else:
#     print(f"요청 실패: {response.status_code}")

CSV 파일이 성공적으로 저장되었습니다.

In [11]:
import pandas as pd

train = pd.read_csv(r'dataset\customer_train.csv')
test = pd.read_csv(r'dataset\customer_test.csv')

train

      회원ID  총구매액  최대구매액  환불금액   주구매상품 주구매지점  방문일수   방문당구매건수    주말방문비율  구매주기
0        0   683    113  69.0      기타   강남점    19  3.894737  0.527027    17
1        1    21     21   3.0     스포츠   잠실점     2  1.500000  0.000000     1
2        2    32     16   NaN  남성 캐주얼   관악점     2  2.000000  0.000000     1
3        3   161     49   NaN      기타   광주점    18  2.444444  0.318182    16
4        4   291    240   NaN      보석  본  점     2  1.500000  0.000000    85
...    ...   ...    ...   ...     ...   ...   ...       ...       ...   ...
3495  3495    32     30   NaN      골프  본  점     1  2.000000  1.000000     0
3496  3496   296     72  60.0    시티웨어  부산본점     8  1.625000  0.461538    40
3497  3497     1      1   NaN    주방용품   창원점     1  1.000000  0.000000     0
3498  3498    19     10   NaN     화장품  본  점     2  1.000000  0.000000    39
3499  3499  2631    346  60.0      기타  본  점    38  2.421053  0.467391     8

[3500 rows x 10 columns]

## <a id='toc3_2_'></a>[데이터 유형 파악](#toc0_)

In [12]:
train.info()
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   회원ID     3500 non-null   int64
 1   총구매액     3500 non-null   int64
 2   최대구매액    3500 non-null   int64
 3   환불금액     1200 non-null   float64
 4   주구매상품    3500 non-null   object
 5   주구매지점    3500 non-null   object
 6   방문일수     3500 non-null   int64
 7   방문당구매건수  3500 non-null   float64
 8   주말방문비율   3500 non-null   float64
 9   구매주기     3500 non-null   int64
dtypes: float64(3), int64(5), object(2)
memory usage: 273.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2482 entries, 0 to 2481
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   회원ID     2482 non-null   int64
 1   최대구매액    2482 non-null   int64
 2   환불금액     867 non-null    float64
 3   주구매상품    2482 non-null   object
 4   주구매지점    2482 non-null   object
 5   방문일수     2482 non-null   int64
 6   방문당구매건수  2482 non-null   float64
 7   주말방문비율   2482 non-null   float64
 8   구매주기     2482 non-null   int64
dtypes: float64(3), int64(4), object(2)
memory usage: 174.6+ KB

## <a id='toc3_3_'></a>[전처리](#toc0_)

### <a id='toc3_3_1_'></a>[(0) 편법으로 빨리하기](#toc0_)

In [ ]:
# (1)

### <a id='toc3_3_2_'></a>[(1) X, y, train/test 분리](#toc0_)

In [16]:
X_train = train.drop(columns=['회원ID', '총구매액'])
y_train = train['총구매액']
X_test = test.drop(columns = ['회원ID'])

In [19]:
print(X_train.shape, X_test.shape, y_train.shape)

(3500, 8) (2482, 8) (3500,)

### <a id='toc3_3_3_'></a>[(2) 결측치 처리](#toc0_)

In [20]:
X_train['환불금액'] = X_train['환불금액'].fillna(0)
X_test['환불금액'] = X_test['환불금액'].fillna(0)

In [22]:
print(X_train.isna().sum())
print(X_test.isna().sum())

최대구매액      0
환불금액       0
주구매상품      0
주구매지점      0
방문일수       0
방문당구매건수    0
주말방문비율     0
구매주기       0
dtype: int64
최대구매액      0
환불금액       0
주구매상품      0
주구매지점      0
방문일수       0
방문당구매건수    0
주말방문비율     0
구매주기       0
dtype: int64

### <a id='toc3_3_4_'></a>[(3) 수치형 변수 스케일링](#toc0_)

In [29]:
X_train.head(3)

   최대구매액  환불금액   주구매상품 주구매지점  방문일수   방문당구매건수    주말방문비율  구매주기
0    113  69.0      기타   강남점    19  3.894737  0.527027    17
1     21   3.0     스포츠   잠실점     2  1.500000  0.000000     1
2     16   0.0  남성 캐주얼   관악점     2  2.000000  0.000000     1

In [ ]:
X_train.columns

Index(['최대구매액', '환불금액', '주구매상품', '주구매지점', '방문일수', '방문당구매건수', '주말방문비율', '구매주기'], dtype='object')

In [34]:
num_cols = ['최대구매액', '환불금액', '방문일수', '방문당구매건수', '주말방문비율', '구매주기']
cat_cols = ['주구매상품', '주구매지점']

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler()

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])         # ※fit_transform 아님 주의

X_train.head(3)

      최대구매액      환불금액   주구매상품 주구매지점      방문일수   방문당구매건수    주말방문비율      구매주기
0  0.020152  0.012238      기타   강남점  0.063380  0.137300  0.527027  0.102410
1  0.007187  0.000532     스포츠   잠실점  0.003521  0.023715  0.000000  0.006024
2  0.006483  0.000000  남성 캐주얼   관악점  0.003521  0.047431  0.000000  0.006024

### <a id='toc3_3_5_'></a>[(4) 범주형 변수 인코딩](#toc0_)

In [36]:
cat_cols

['주구매상품', '주구매지점']

In [43]:
# train에 없는 category가 test에 있을 시 확인

for cc in cat_cols:
    print(cc)
    print('train - test **************', set(X_train[cc]) - set(X_test[cc]))
    print('test - train **************',set(X_test[cc]) - set(X_train[cc]))

주구매상품
train - test ************** {'소형가전'}
test - train ************** set()
주구매지점
train - test ************** set()
test - train ************** set()

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for cc in cat_cols:
    X_train[cc] = encoder.fit_transform(X_train[cc])
    X_test[cc] = encoder .transform(X_test[cc])


X_train.head()

      최대구매액      환불금액  주구매상품  주구매지점      방문일수   방문당구매건수    주말방문비율      구매주기
0  0.020152  0.012238      5      0  0.063380  0.137300  0.527027  0.102410
1  0.007187  0.000532     21     19  0.003521  0.023715  0.000000  0.006024
2  0.006483  0.000000      6      1  0.003521  0.047431  0.000000  0.006024
3  0.011133  0.000000      5      2  0.059859  0.068511  0.318182  0.096386
4  0.038050  0.000000     15      8  0.003521  0.023715  0.000000  0.512048

## <a id='toc3_4_'></a>[데이터 분리(train,val)](#toc0_)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = 0.2, random_state = 42)
# 분류의 경우 train_test_split(X_train, y_train, test_size = 0.2, stratify=y)
print(X_train.shape, X_val.shape, y_train.shape, y_val.shape)

(2800, 8) (700, 8) (2800,) (700,)

## <a id='toc3_5_'></a>[모델 학습 및 검증](#toc0_)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
# 분류의 경우 RandomForestClassifier

model = RandomForestRegressor()

model.fit(X_train,y_train)
y_val_pred = model.predict(X_val)

# # 분류의 경우 예측 결과 숫자를 다시 문자열로 변환
# predictions_str = label_encoder.inverse_transform(predictions)

## <a id='toc3_6_'></a>[평가](#toc0_)

In [48]:
from sklearn.metrics import root_mean_squared_error, r2_score

rmse = root_mean_squared_error(y_val, y_val_pred)
r2 = r2_score(y_val, y_val_pred)

print(rmse, r2)

795.8416353525819 0.75840008512395

## <a id='toc3_7_'></a>[결과 제출](#toc0_)

In [50]:
y_pred = model.predict(X_test)

result = pd.DataFrame(y_pred, columns = ['pred'])

result.to_csv('result.csv', index = False)

In [51]:
# 다시 체크

df = pd.read_csv('result.csv')
df

         pred
0     1998.97
1     4769.08
2     3720.46
3      895.54
4      559.57
...       ...
2477  1422.67
2478   421.47
2479  2974.45
2480  1184.68
2481   592.63

[2482 rows x 1 columns]